spec:
  ingresses:
    - "https://sf-nada-platforce.intern.nav.no"
  gcp:
    bigQueryDatasets:
      - name: license
        permission: READWRITE
  env:
    - name: POST_TO_BIGQUERY
      value: 'true'
    - name: EXCLUDE_TABLES
      value: 'active-feature-license-staging,active-feature-license-metric,active-permset-license-metric,active-salesforce-user-v2-staging,community-user-login-v2'

