spec:
  ingresses:
    - "https://sf-nada-platforce.intern.nav.no"
  gcp:
    bigQueryDatasets:
      - name: license
        permission: READWRITE
  env:
    - name: POST_TO_BIGQUERY
      value: 'true'
    - name: EXCLUDE_TABLES
      value: 'network,active-feature-license'

