spec:
  ingresses:
    - "https://sf-nada-platforce.intern.nav.no"
  gcp:
    bigQueryDatasets:
      - name: license
        permission: READWRITE
  envFrom:
    - configmap: salesforce-common
    - secret: migration-prod
    - secret: sf-nada-prod
  env:
    - name: POST_TO_BIGQUERY
      value: 'true'
    - name: EXCLUDE_TABLES
      value: ''

