spec:
  ingresses:
    - "https://sf-nada-dialog-tmp.intern.nav.no"
  gcp:
    bigQueryDatasets:
      - name: arbeidsgiver_aktivitet
        permission: READWRITE
      - name: arbeidsgiver_diverse
        permission: READWRITE
  env:
    - name: POST_TO_BIGQUERY
      value: 'true'
    - name: EXCLUDE_TABLES
      value: ''