apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sf-nada
  namespace: replace-with-namespace
  labels:
    team: replace-with-namespace
spec:
  image: '{{ image }}'
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    logging:
      destinations:
        - id: loki
  resources:
    limits:
      memory: 3Gi
    requests:
      cpu: 10m
      memory: 1Gi
  envFrom:
    - secret: sf-nada-preprod
  accessPolicy:
    outbound:
      external:
        - host: test.salesforce.com
        - host: navdialog--preprod.sandbox.my.salesforce.com
  env:
    - name: MAPDEF_FILE
      value: '/mapdef/replace-with-namespace/dev.json'
    - name: SF_TOKENHOST
      value: 'https://test.salesforce.com'
    - name: SALESFORCE_VERSION
      value: 'v65.0'
    - name: DEPLOY_CLUSTER
      value: '{{ DEPLOY_CLUSTER }}'